# Generated by Django 5.0.1 on 2024-02-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_follower_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='first_name',
            field=models.CharField(default='james', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follower',
            name='last_name',
            field=models.CharField(default='mahboul', max_length=60),
            preserve_default=False,
        ),
    ]
